sequenceDiagram
        actor Browserclient
        actor Server
        Browserclient->>Server: GET https://studies.cs.helsinki.fi/exampleapp/spa
        Server->>Browserclient: HTML Doc(include main.css, spa.js, & data.json)
        Browserclient->>Server: push note to data.json
        Server->>Browserclient: response https://studies.cs.helsinki.fi/exampleapp/new_note_spa

