flowchart TD
    %% GET https://studies.cs.helsinki.fi/exampleapp/notes include main.css and main.js
    A[Browser] -->|Get notes| B(Server) 
    %% Response from server to browser
    B(Server) -->|HTML Doc| A[Browser]
    %% POST json to server
    A --> |POST json| B(Server)
        %% GET data.json from
        B --> |css file| A[Browser]
        B --> |js file| A[Browser]
        B --> |return notes| A[Browser]
